# Generated by Django 5.2.16 on 2026-09-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_opening_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('generalist', 'Generalist'), ('fresher', 'Fresher / Entry-level'), ('default', 'Default')], default='default', help_text='Controls how Score Candidates weighs skills vs experience vs education for this role.', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='must_have_requirements',
            field=models.TextField(blank=True, help_text='One requirement per line. A candidate missing one is flagged for HR review rather than having their score reduced for it.', null=True, verbose_name='Must-Have Requirements'),
        ),
    ]
