# Generated by Django 5.2.16 on 2026-08-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_bulkuploadbatch_bulkuploaditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='role_applied',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Applied Position'),
        ),
    ]
