# Generated by Django 5.2.16 on 2026-08-21 07:10

from django.db import migrations, models

HOLD = 'SCREENING_HOLD'


def backfill_hold_stage(apps, schema_editor):
    """Name the holds that already exist after the stage they were taken at,
    reading it back from the status history."""
    Candidate = apps.get_model('candidates', 'Candidate')
    History = apps.get_model('candidates', 'CandidateStatusHistory')
    for candidate in Candidate.objects.filter(status=HOLD):
        last_hold = (History.objects.filter(candidate=candidate, new_status=HOLD)
                     .order_by('-changed_at', '-id').first())
        if last_hold and last_hold.old_status:
            candidate.hold_from_status = last_hold.old_status
            candidate.save(update_fields=['hold_from_status'])


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_candidate_role_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='hold_from_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SHORTLISTED', 'Shortlisted'), ('ROUND1', 'Round 1'), ('INTERVIEW', 'Interview'), ('FINAL_SELECTION', 'Final Selection'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('BLACKLISTED', 'Blacklisted'), ('SCREENING_HOLD', 'Hold')], default='OPEN', max_length=30),
        ),
        migrations.RunPython(backfill_hold_stage, migrations.RunPython.noop),
    ]
