# Generated by Django 5.2.16 on 2026-09-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_candidate_hold_from_status_alter_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='match_breakdown',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='match_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='match_rationale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='match_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='match_scored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='match_state',
            field=models.CharField(choices=[('PENDING', 'Not scored'), ('SCORING', 'Scoring'), ('DONE', 'Scored'), ('ERROR', 'Failed')], default='PENDING', max_length=10),
        ),
    ]
