# Generated by Django 5.2.16 on 2026-09-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_candidate_match_breakdown_candidate_match_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cv_summary_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='cv_summary_state',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Regenerating'), ('ERROR', 'Failed')], default='IDLE', max_length=10),
        ),
    ]
