# Generated by Django 5.2.16 on 2026-09-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_alter_candidate_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='cv_summary_error',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='cv_summary_state',
        ),
    ]
