# Generated by Django 5.2.16 on 2026-09-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0015_remove_candidate_cv_summary_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SHORTLISTED', 'Qualified'), ('ROUND1', 'Round 1'), ('INTERVIEW', 'Round 2'), ('FINAL_SELECTION', 'Final Selection'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected'), ('BLACKLISTED', 'Blacklisted'), ('SCREENING_HOLD', 'Hold')], default='OPEN', max_length=30),
        ),
    ]
