# Generated by Django 5.2.16 on 2026-09-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_alter_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='screening_questions',
            field=models.TextField(blank=True, null=True, verbose_name='Tele Screening Questions'),
        ),
    ]
