# Generated by Django 5.2.16 on 2026-09-14 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_scoringcriteria_per_job'),
        ('jobs', '0005_job_job_type_job_must_have_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='suggested_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='future_prospect_candidates', to='jobs.job'),
        ),
    ]
