# Generated by Django 5.2.16 on 2026-09-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0020_candidate_suggested_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestatushistory',
            name='is_undone',
            field=models.BooleanField(default=False),
        ),
    ]
