# Generated by Django 5.2.16 on 2026-09-03 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interviewreschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='interviewreschedule',
            name='changed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
