# Generated by Django 5.2.16 on 2026-09-09 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0017_candidate_screening_questions'),
        ('interviews', '0005_alter_interview_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('ROUND1', 'Round 1'), ('TECHNICAL', 'Technical'), ('MANAGERIAL', 'Managerial'), ('FINAL', 'Final'), ('HR', 'HR Round')], default='ROUND1', max_length=20)),
                ('mode', models.CharField(choices=[('ONSITE', 'Onsite'), ('PHONE', 'Phone'), ('VIDEO', 'Video')], default='VIDEO', max_length=20)),
                ('status', models.CharField(choices=[('AWAITING_SLOTS', 'Awaiting Slots'), ('AWAITING_SELECTION', 'Awaiting HR Selection'), ('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled')], default='AWAITING_SLOTS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_requests', to='candidates.candidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interviews.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='interviews.interviewrequest')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
