# Generated by Django 5.2.16 on 2026-09-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_interviewrequest_interviewslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
