# Generated by Django 5.2.16 on 2026-09-16 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_alter_interview_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewrequest',
            name='candidate_selected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='candidate_selected_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interviews.interviewslot'),
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='candidate_token',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='interviewrequest',
            name='slots_proposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewrequest',
            name='status',
            field=models.CharField(choices=[('AWAITING_SLOTS', 'Awaiting Slots'), ('AWAITING_SELECTION', 'Awaiting Candidate Selection'), ('AWAITING_HR_APPROVAL', 'Awaiting HR Approval'), ('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled')], default='AWAITING_SLOTS', max_length=20),
        ),
    ]
