# Generated by Django 5.2.16 on 2026-09-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0009_interviewrequest_candidate_selected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='round_type',
            field=models.CharField(choices=[('ROUND1', 'Round 1'), ('ROUND2', 'Round 2'), ('TECHNICAL', 'Technical'), ('MANAGERIAL', 'Managerial'), ('FINAL', 'Final'), ('HR', 'HR Round')], default='ROUND1', max_length=20),
        ),
        migrations.AlterField(
            model_name='interviewrequest',
            name='round_type',
            field=models.CharField(choices=[('ROUND1', 'Round 1'), ('ROUND2', 'Round 2'), ('TECHNICAL', 'Technical'), ('MANAGERIAL', 'Managerial'), ('FINAL', 'Final'), ('HR', 'HR Round')], default='ROUND1', max_length=20),
        ),
    ]
